version: 2
jobs:
  test-node10:
    docker:
      - image: circleci/node:10
    steps: &test-steps
      - checkout
      - run:
          name: install-npm
          command: npm install
      - run:
          name: test
          command: npm test
  test-node8:
    docker:
      - image: circleci/node:8
    steps: *test-steps
  test-node6:
    docker:
      - image: circleci/node:6
    steps: *test-steps
  build_and_deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: install-npm
          command: npm install
      - run:
          name: build
          command: npm run build
      - run:
          name: prepare
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
      - run:
          name: publish
          command: |
            npm publish

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test-node10
          filters:
            tags:
              only: /^v.*/
      - test-node8
          filters:
            tags:
              only: /^v.*/
      - test-node6
          filters:
            tags:
              only: /^v.*/
      - build_and_deploy:
          requires:
            - test-node10
            - test-node8
            - test-node6
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
