version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: install-npm
          command: npm install
      - run:
          name: test
          command: npm test
  deploy:
    steps:
      - run:
          name: prepare
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
      - run:
          name: publish
          command: |
            npm publish

workflows:
  version: 2
  build_and_deploy:
    machine: true
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
            
      
